-- 코드를 입력하세요
WITH 
TWO_CAR_TYPE AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('세단', 'SUV') 
),
WHOSE_DISCOUNT AS (
    SELECT TT.CAR_ID, TT.DAILY_FEE, P.CAR_TYPE, P.DISCOUNT_RATE
    FROM TWO_CAR_TYPE TT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON TT.CAR_TYPE = P.CAR_TYPE
    WHERE P.DURATION_TYPE='30일 이상'  
)

SELECT W.CAR_ID, W.CAR_TYPE, TRUNCATE(W.DAILY_FEE*(100-W.DISCOUNT_RATE)*0.01*30, 0) AS FEE
FROM WHOSE_DISCOUNT W LEFT  JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON W.CAR_ID=H.CAR_ID 
    AND H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
WHERE H.CAR_ID IS NULL 
    AND W.DAILY_FEE*(100-W.DISCOUNT_RATE)*0.01*30 >= 500000 AND W.DAILY_FEE*(100-W.DISCOUNT_RATE)*0.01*30 < 2000000
ORDER BY 
    FEE DESC, 
    W.CAR_TYPE ASC, 
    H.CAR_ID DESC

# SELECT DISTINCT 
#     C.CAR_ID, 
#     C.CAR_TYPE, 
#     TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
# FROM 
#     CAR_RENTAL_COMPANY_CAR C
# INNER JOIN 
#     (SELECT CAR_TYPE, DISCOUNT_RATE
#      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#      WHERE DURATION_TYPE = '30일 이상'
#     ) P ON C.CAR_TYPE = P.CAR_TYPE
# LEFT JOIN 
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
#     AND (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01')
# WHERE 
#     C.CAR_TYPE IN ('세단', 'SUV')
#     AND H.CAR_ID IS NULL
#     AND TRUNCATE(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) BETWEEN 500000 AND 1999999
# ORDER BY 
#     FEE DESC, 
#     C.CAR_TYPE, 
#     C.CAR_ID DESC;