-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR, 
        EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT(O.USER_ID)) AS PUCHASED_USERS,
        ROUND(COUNT(DISTINCT(O.USER_ID))/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE DATE_FORMAT(JOINED, '%Y')='2021'),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O 
JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE DATE_FORMAT(JOINED, '%Y')='2021'
) i
ON I.USER_ID=O.USER_ID 
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC