-- 코드를 입력하세요
# SELECT CAR_ID,START_DATE,END_DATE,
#     CASE
#         WHEN '2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT(END_DATE, '%Y-%m-%d')
#         THEN '대여중'
#         ELSE '대여 가능'
#     END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING MAX(END_DATE)
# ORDER BY CAR_ID DESC

WITH IDS AS (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ORDER BY CAR_ID
) 

SELECT I.CAR_ID,
    CASE
        WHEN H.HISTORY_ID IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM IDS I LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON I.CAR_ID = H.CAR_ID AND '2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT(END_DATE, '%Y-%m-%d')
ORDER BY I.CAR_ID DESC
    