-- 코드를 입력하세요
WITH HISTORY_DURATION AS (
SELECT H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DURATION,
   CASE
   WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 7 THEN NULL
   WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 30 THEN '7일 이상'
   WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 90 THEN '30일 이상'
   ELSE '90일 이상' END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID=H.CAR_ID
WHERE C.CAR_TYPE = '트럭'
)

SELECT D.HISTORY_ID,
    ROUND(D.DAILY_FEE * D.DURATION * IFNULL((1-P.DISCOUNT_RATE/100), 1)) AS FEE
FROM HISTORY_DURATION D LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON D.DURATION_TYPE=P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, D.HISTORY_ID DESC