# -- 코드를 입력하세요
WITH CH AS
(SELECT H.HISTORY_ID, C.DAILY_FEE, C.CAR_TYPE, DATEDIFF(H.END_DATE,H.START_DATE)+1 AS DATEDIFF,
    CASE
        WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1>=90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1>=30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1>=7 THEN '7일 이상'
        ELSE '0일 이상'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID AND C.CAR_TYPE='트럭')
                    
SELECT CH.HISTORY_ID, ROUND(CH.DAILY_FEE*(1-IFNULL(P.DISCOUNT_RATE,0)/100)*DATEDIFF,0) AS FEE
FROM CH LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON CH.CAR_TYPE = P.CAR_TYPE AND CH.DURATION_TYPE=P.DURATION_TYPE
ORDER BY FEE DESC, CH.HISTORY_ID DESC