-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM CTE
    WHERE HOUR < 23
),
ANIMAL_COUNTS AS (
    SELECT EXTRACT (HOUR FROM DATETIME) HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY EXTRACT (HOUR FROM DATETIME)
)

SELECT C.HOUR, IFNULL(A.COUNT, 0) AS COUNT
FROM CTE C LEFT JOIN ANIMAL_COUNTS A ON C.HOUR=A.HOUR
ORDER BY HOUR
