# SELECT *
# FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID=R.MEMBER_ID




SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (REST_REVIEW R JOIN MEMBER_PROFILE P ON R.MEMBER_ID=P.MEMBER_ID)
    JOIN (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) AS M
    ON P.MEMBER_ID=M.MEMBER_ID
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC