-- 코드를 작성해주세요
WITH YEAR_SIZE AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (Y.MAX-E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E JOIN YEAR_SIZE Y ON YEAR(E.DIFFERENTIATION_DATE)=Y.YEAR
ORDER BY Y.YEAR ASC, YEAR_DEV ASC
