-- 코드를 입력하세요
SELECT  PRODUCT_CODE, SUM(O_L.SALES_AMOUNT) * P.PRICE AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O_L ON P.PRODUCT_ID = O_L.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE
