-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = 
    (SELECT B1.BOARD_ID
     FROM USED_GOODS_BOARD B1
     WHERE NOT EXISTS(
         SELECT *
         FROM USED_GOODS_BOARD B2
         WHERE B1.VIEWS < B2.VIEWS
     )
    )
ORDER BY FILE_ID DESC