-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',F.FILE_ID, F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B RIGHT OUTER JOIN USED_GOODS_FILE F
    ON B.BOARD_ID=F.BOARD_ID
WHERE F.BOARD_ID = (
    SELECT K.BOARD_ID
    FROM USED_GOODS_BOARD K
    ORDER BY VIEWS DESC
    LIMIT 1
)
ORDER BY FILE_PATH DESC