-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE (A.CATEGORY, A.PRICE) IN (
    SELECT B.CATEGORY,MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT B
    WHERE B.CATEGORY IN ( '과자', '국', '김치', '식용유')
    GROUP BY B.CATEGORY
)
ORDER BY A.PRICE DESC
